### get all users
GET http://localhost:4000/user-api/users

###add user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"dsp",
    "age":70,
    "email":"abcd@gmail.com",
    "DOB":"2005-10-18",
    "phone":7396006897
}

###update user or deactivate
DELETE http://localhost:4000/user-api/users/69a68224522ad96e2fe128eb

###activate user
PATCH http://localhost:4000/user-api/users/69a68224522ad96e2fe128eb